version: "3"
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - prisma/dev-db.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432

volumes:
  database-data: # named volumes can be managed easier using docker-compose

# taken from https://medium.com/analytics-vidhya/getting-started-with-postgresql-using-docker-compose-34d6b808c47c
