version: "3"
services:
  database:
    image: postgres:13
    env_file:
      - db/dev-db.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 6692:5432

  s3:
    image: minio/minio:RELEASE.2020-10-12T21-53-21Z
    command: server /data
    environment:
      MINIO_ACCESS_KEY: test-minio-access
      MINIO_SECRET_KEY: test-minio-secret
    ports:
      - 6698:9000
    volumes:
      - s3-data:/data

volumes:
  database-data:
  s3-data:
