version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8
  working_directory: ~/project

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - yarn-dependencies-{{ checksum "yarn.lock" }}
      - run: |
          yarn install --frozen-lockfile --network-concurrency 1
      - save_cache:
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
          paths: ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths: .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
          yarn run lint
  tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn test -- --coverage
      - store_artifacts:
          path: coverage
          destination: coverage
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
          sudo apt install rsync
          yarn global add heroku
          yarn deploy aven-io
workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - tests:
          requires:
            - install-dependencies
      - deploy:
          requires:
            - lint
            - tests
