name: Deploy

on:
  push:
    branches: main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SKY_DEPLOY_KEY: ${{ secrets.SKY_DEPLOY_KEY }}
        run: |
          mkdir /home/runner/.ssh
          echo "$SKY_DEPLOY_KEY" | base64 --decode > /home/runner/.ssh/id_rsa
          chmod go-rwx /home/runner/.ssh/id_rsa
          echo "sky.aven.io,88.198.34.150 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKQl3ounloUClxrJFJMOOioHdxnrY9UqD2lQVCJjzlBHCscxo9vGvHDZCUCwkxOfBJlEIAEZ1xCuc4C71PWS+X8=" >> /home/runner/.ssh/known_hosts
          ssh root@sky.aven.io -t "cd /var/www/sky && git pull && ./scripts/deploy.sh"