name: Test Suite

on:
  push:
    branches: [main]

jobs:
  build:
    name: Basic Tests
    runs-on: ubuntu-latest
    steps:
      - name: Yarn
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
