name: Wing

on:
  push:
    branches:
      - 'master'

jobs:
  production:
    name: Production Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest
        uses: AvenCloud/actions/checkout@v1

      - name: Build Application
        # https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers#the-technical-details
        run: |
          sudo sysctl fs.inotify.max_user_watches=524288
          sudo sysctl -p

          yarn wing:build

      - name: Deploy to Runtime Server
        uses: AvenCloud/actions/deploy@v1
        with:
          deploy-key: ${{ secrets.DEPLOY_KEY }}

  test-live:
    needs: [production]
    name: Test Live Server for errors
    runs-on: ubuntu-latest

    steps:
      - name: Smoke Test
        run: wget --spider --recursive --no-directories --no-verbose --reject-regex "&quot;data:image/png;base64" --execute robots=off --level=0 --span-hosts -D "*.aven.io" -D aven.io https://wing.aven.io
